#!/bin/bash

mkdir -p archives

export TZ=`cat /etc/timezone`
timestamp=`date +%Y-%m-%dT%H%M`
databases=$(psql -tqc "SELECT datname FROM pg_database WHERE datistemplate = false AND datname <> 'postgres';" postgres)
for d in $databases; do
  pg_dump $d | gzip > archives/${timestamp}_$d.sql.gz
done
