- hosts: all
  remote_user: "{{ user }}"
  sudo: true
  vars_files:
    - vars.yml
  roles:
  - { role: common }
  - { role: ruby }
  - { role: passenger }
  - { role: app_server }
  - { role: db_server }
