- name: install pre-requisites
  apt: pkg=apt-transport-https

- name: apt key
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x561F9B9CAC40B2F7

- name: apt repository
  apt_repository: "repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ ansible_distribution_release }} main'"

- name: install
  apt: pkg={{ item }} state=latest
  register: passenger
  with_items:
    - nginx-extras
    - passenger

- name: enable nginx module
  lineinfile: dest=/etc/nginx/nginx.conf regexp='passenger_root' line='passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;'

- name: disable default site
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: ufw | allow http
  ufw: rule=allow port=80 protocol=tcp
  register: ufw_updated
  tags: ufw

