# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3d0140eb8640d7a68142c0a997f4fdb6bde14d14720caa26ab0c6e92c98b388b697e1985fe319ed51887bf79b8083085a9c94ebd829479e994f56ea29a305ff

test:
  secret_key_base: da3de5f9eb3523fdeea28da59b8e164bdc3b8754b9bda34b4d35c06ce9c35df76fd1694d9fce4ef98deaac58d3c5cd5b0d8eb3eb4c25fa9336e4cba87e5c7ac3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
