- debug: msg=Installing ruby v{{ ruby_version }}
  tags: ruby

- name: install pre-requisites
  apt: pkg={{ item }}
  with_items:
    - git
    - build-essential
    - python-setuptools
    - python-dev
    - python-pycurl
    - zlib1g
    - zlib1g-dev
    - libffi-dev
    - libpq-dev
    - libreadline6
    - libreadline6-dev
    - libssl-dev
    - ruby-dev
    - libcurl4-openssl-dev
    - ntp
    - logrotate
  tags: ruby

- name: clone rbenv repository
  git: accept_hostkey=yes repo=git://github.com/sstephenson/rbenv.git dest=/usr/local/rbenv
  tags: ruby

- name: configure rbenv environment
  copy: src=rbenv.sh dest=/etc/profile.d/rbenv.sh mode=0755
  tags: ruby

- name: set environment variables
  lineinfile: dest=/etc/environment regexp='{{ item.regexp }}' line='{{ item.line }}'
  with_items:
    - { regexp: 'RBENV_ROOT=', line: 'RBENV_ROOT={{ rbenv_env.RBENV_ROOT }}' }
    - { regexp: 'PATH=', line: 'PATH={{ rbenv_env.PATH }}' }
  tags: ruby

- name: install ruby-build
  git: repo=git://github.com/sstephenson/ruby-build.git dest=/usr/local/rbenv/plugins/ruby-build
  tags: ruby

- name: install ruby
  command: rbenv install {{ ruby_version }} creates=/usr/local/rbenv/versions/{{ ruby_version }}
  environment: rbenv_env
  register: rubyinstalled
  tags: ruby

- name: set default ruby
  command: rbenv global {{ ruby_version }}
  environment: rbenv_env
  when: rubyinstalled.changed
  tags: ruby

- name: defaults for rubygems
  copy: src=gemrc dest={{ item }}
  with_items:
    - /etc/gemrc
    - /root/.gemrc
    - /etc/skel/.gemrc
    - /home/{{ user }}/.gemrc
  tags: ruby

- name: install bundler
  command: rbenv exec gem install bundler creates=/usr/local/rbenv/versions/{{ ruby_version }}/bin/bundle
  environment: rbenv_env
  register: bundler_installed
  tags: ruby

- name: rehash
  command: rbenv rehash
  environment: rbenv_env
  when: bundler_installed.changed
  tags: ruby
